### ISSUE TITLE
Change the blade motor rotation direction

### ISSUE THREAD

**Issue by bdevijve** [ClemensElflein/OpenMower#15]
I'don't know if this feature is already enabled, but I just found this picture from einhell datasheet wich seems interresting:

![image](https://user-images.githubusercontent.com/74436690/167289201-ef57216c-45ae-4ce9-9924-7d487d5b9ee0.png)

**Comment by ClemensElflein** [comment]
done: https://github.com/ClemensElflein/open_mower_ros/pull/43
