### ISSUE TITLE
Enable Low Level Emergency Deactivation (Button)

### ISSUE THREAD

**Issue by endoskop27** [ClemensElflein/OpenMower#16]
**Problem Statement:** 
Since the Mainboard of the Robotic Mower has been substituted the emergency Stop button functionality is assumed not to be working. This part is one of the most important safety measures beside the Gyroscope based deactivation of the mower, I propose to integrate a low-level emergency switch which deactivates the Motors.

Expected Behavior:
- If Emergency Button is pressed the Robot stops mowing instantly and requires manual reset
- The low Level Controller (PiCO or similar) requires an reinitialization routine from Raspberry in order to restart operation
- Saving the location and time of event on storage

Proposed approaches:
- Hardware based Kill-switch cutting the motor driver voltages
- Software based ISR listening on the Emergency Button Pin and actively deactivates motors

**Comment by ClemensElflein** [comment]
your assumption is wrong, the emergency button works as you describe. mower goes into emergency and needs to be unlocked manually
