### ISSUE TITLE
Website SSL Error

### ISSUE THREAD

**Issue by admbradford** [ClemensElflein/OpenMower#2]
Receiving an `ERR_SSL_PROTOCOL_ERROR` when visiting your blog site https://x-tech.online/

**Comment by ClemensElflein** [comment]
Thank you for the report. It's working fine for me even in a private tab. Which browser are you using? What's the error message you're getting?

**Comment by admbradford** [comment]
I’m on mobile chrome v100.0.4896.77 iOS 15.4.1

here’s a screen shot

![53C1C284-0033-4C04-AEF6-98B5F0376C93](https://user-images.githubusercontent.com/2473425/162436590-0798c9ea-be0e-403f-be72-ea64506d25d5.jpeg)

**Comment by admbradford** [comment]
I checked off my home network and it worked fine, I have some aggressive protection from my router. It’s likely due to the second cert

[SSL Server Test: x-tech.online (Powered by Qualys….pdf](https://github.com/ClemensElflein/OpenMower/files/8451909/SSL.Server.Test.x-tech.online.Powered.by.Qualys.pdf)

**Comment by ClemensElflein** [comment]
Thank you for the info! I'm looking into it. To be honest, I'm just using the Let's Encrypt Certbot and was glad that it seemed to work out. There has to be some strange configuration still.
