### ISSUE TITLE
Is there a way to adjust blade height?

### ISSUE THREAD

**Issue by vipasane** [ClemensElflein/OpenMower#33]
Actually this is more of a question or a feature request.
So is there a way to adjust blade height?
In my yard there are places that I would like blade to be lower and places where it should not be as low or it might hit something 
Also this would be a great feature combined with other feature requests, while having different patterns in place one could make all kinds of nice patterns like on a football fields.
[Pic for reference](https://www.istockphoto.com/fi/vektori/jalkapallokentt%C3%A4-jalkapallokentt%C3%A4-ruohonleikkuu-kuviot-gm544356192-97829765l)

**Comment by docgalaxyblock** [comment]
Unfortunate the YardForce mowers have not way to automatically adjust the height cause they use a big thread around the mowing motor chassi part there manual adjustment is mandatory

*maybe in the future of the project some crazy 3d printing people develop a solution - maybe*
