### ISSUE TITLE
How to start to build the mower? 

### ISSUE THREAD

**Issue by chicco83** [ClemensElflein/OpenMower#4]
Hi.
I'm very interested in the project but It Is not clear how to start the hardware part. Which parts to buy, if It Is mandatory to have a dedicated PCB produced ecc

**Comment by r00li** [comment]
Yeah I too would be interested in a bit more detailed guide of what exactly needs to be purchased, which PCBs made, ... 

I had a look at the BOM and it seems a bit incomplete - it seems to only cover the main board components, but doesn't include things like the GPS receiver, ...

**Comment by GruNyv** [comment]
Based on the video he posted, the gps receiver is a simplertk2b (with a zed-f9p GNSS module) and a u-blox multiband antenna. These are relatively cheap, around 200 euros, considering that other brands usually cost several thousand euros.

**Comment by Kisses99** [comment]
Maybe it's even cheaper to hook up an old smartphone.

**Comment by GruNyv** [comment]
@Kisses99 The problem is that your smartphone is not RTK compatible. You need a GNSS module that supports RTK, such as the ZED-F9P.

**Comment by Kisses99** [comment]
Ah got it.
But it really stacked up the cost and made this build less attractive though.

**Comment by GruNyv** [comment]
Yes, the cost of RTK certainly is a barrier to entry. This was especially true before the ZED-F9P, where it was mostly reserved for the industry and extreme hobbyists. Another issue is that you might need 2 of them, where one acts as a base station, if there are no freely available base stations near you through i.e. RTK2GO and you don't want to pay for a commerical subscription

**Comment by FadeFx** [comment]
@Kisses99 there are cheaper optiins as well, but i guess they dont provide enough precission for a task like that. Did you ever check the precission of your smartphone gps? its most likely not below 5m...

**Comment by GruNyv** [comment]
Unless you use some sort of differential gnss (which RTK is a subgroup of), you can't expect better accuracy than 3-10 meters depending on the conditions. Compare that to RTK which has an accuracy of < 2 cm.

**Comment by Kisses99** [comment]
@FadeFx right that's what I just figured.  However I'm still concerned that gps accuracy may be significantly impacted by shades of trees.  For an open yard this may just be fine.

**Comment by GruNyv** [comment]
Yes, the tree shades and buildings is what I am concerned with. I have been working with this exact model during this spring and it often has troubles when you enter non-open areas

**Comment by FadeFx** [comment]
could it be possible to compensate this by also taking in account your actual movement? I mean from the motor controlls

**Comment by GruNyv** [comment]
You certainly can predict your movement using multiple sensors by a kalman filter. However, it might work to simply drive randomly when you are in a region without signal, since this is what they already do. The issue is of course the possible lack of boundary wire

**Comment by mischla** [comment]
> Yes, the cost of RTK certainly is a barrier to entry. This was especially true before the ZED-F9P, where it was mostly reserved for the industry and extreme hobbyists. Another issue is that you might need 2 of them, where one acts as a base station, if there are no freely available base stations near you through i.e. RTK2GO and you don't want to pay for a commerical subscription

Is the German SAPOS system which provides Ntrip in RTCM 3.1 format what would be needed here?

**Comment by GruNyv** [comment]
@mischla Most network RTK providers which uses RTCM 3 should work, but you should check out which satellite constelletions they provide corrections for (GPS, Galileo, GLONASS...)

**Comment by mischla** [comment]
Thanks for the quick answer, in this case all of the mentioned.
Link below in German valid for NRW: https://gppspro.saposnrw.de/service.php

**Comment by stilsch** [comment]
Maybe a look at ardumower.de and it's Sunray (GPS-RTK) firmware might also help you https://github.com/Ardumower/Sunray

**Comment by Bojkas1985** [comment]
Hi, wouldn't some form of triangulation using bluetooth iBeacon be possible?

**Comment by fsommer1968** [comment]
> Hi, wouldn't some form of triangulation using bluetooth iBeacon be possible?

What is the accuracy you can achieve?
Everything more than a few (more than 10cm) over the complete backyard is just not acceptable!

**Comment by GruNyv** [comment]
From what I could find on the Internet, the accuracy is at best one meter, which is not good enough to be used for control. Could maybe be used as a backup if you add a safety zone on 1 meter from the perimeter when you don't have RTK, but it will of course increase the price of the already pretty expensive build

**Comment by lightheaded** [comment]
Hi! Coming back to the initial question, would it be possible to add a "getting started" section to the readme? I have extensive software background and I tinker with some electronics, but I've never created my own PCB. Looking at the project, I have the same problem as @chicco83 - where to start?

**Comment by vamatis** [comment]
Have a look at the wiki. Most of the needed infos are there...
If in doubt, just ask in the discord

**Comment by lightheaded** [comment]
Thanks for pointing me that way! Here's the link for those still lost: https://wiki.openmower.de/index.php?title=Main_Page#How_to_Get_Started

Edit: also added a PR to add this info to the README: https://github.com/ClemensElflein/OpenMower/pull/29

**Comment by rfvermut** [comment]
There is a better guide now: https://openmower.de/docs/getting-started/
