### ISSUE TITLE
Add issues for development

### ISSUE THREAD

**Issue by conradkirschner** [ClemensElflein/OpenMower#9]
Since there are some open tasks todo (e.g. build an app) I would be super happy about a roadmap/some "good starting point" tickets. 

Maybe a Roadmap is a good starting point, from there we could create some tickets/tasks and some kind of structure (tags)

**Comment by ghost** [comment]
Hi,

We are working on having the roadmap available on the wiki :)
Hopefully it will be online soon!

**Comment by pedromorgan** [comment]
Its a "mediawiki install" > https://wiki.openmower.de/index.php?title=Main_Page

Need to discuss this.. and basically a markdown site would suffice in most cases...
- the backend and hosting of this is a huge burden into future.. imho...

gitlab pages and Ci is a free versionable and same caper, but a static website instead...#

**Comment by pedromorgan** [comment]
Can help  with replacing wikimedia.. sooner the better..
