### ISSUE TITLE
Last main board pinout

### ISSUE THREAD

**Issue by roque-canales** [ClemensElflein/OpenMower#91]
Hello, i just ordered last mainboard, and i plan to install it in my old l200e robot mower (3 brushless motor) and i need the pinout of the last openmower mainboard to install it. Also i need to tune the esc with vesc software so in need to know where to connect the usb to set the vesc software ( are the vesc foc included foc capable or only bdlc?)
Thank you

**Comment by ClemensElflein** [comment]
Schematic of the mainboard is hosted here: https://clemenselflein.github.io/OpenMower/

The ESCs have both FOC and BLDC support. It's based on an older version of VESC, but the latest firmware can also be built for the ESCs. For more information about that check the Discord (x-esc channel).
